FROM node:20-alpine AS base
RUN apk add --no-cache openssl libssl3

FROM base AS deps
RUN apk add --no-cache libc6-compat openssl libssl3
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

FROM base AS dev
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npx prisma generate

ENV PORT=8000
EXPOSE 8000
CMD ["npm", "run", "dev"]
