FROM node:20-alpine AS base
RUN apk add --no-cache openssl libssl3 libc6-compat

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install

# Copy source code
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Expose port
EXPOSE 8000

ENV PORT=8000
ENV NODE_ENV=development
ENV HOSTNAME="0.0.0.0"

# Run development server
CMD ["npm", "run", "dev"]
